import type { Metadata } from "next";
import "../../presentation/styles/globals.css";
import { NavBar } from "@/presentation/components/ui/nav-bar/NavBar.tsx";
import { SideBar } from "@/presentation/components/ui/side-bar/SideBar.tsx";

export const metadata: Metadata = {
  title: "EdYOf Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main className="flex w-full py-4 pr-4">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
